--TEST--
GH-10695: Exceptions in resource dtors during shutdown are caught
--EXTENSIONS--
crex_test
--FILE--
<?crx
set_exception_handler(function (\Throwable $exception) {
    echo 'Caught: ' . $exception->getMessage() . "\n";
});

$resource = crex_test_create_throwing_resource();
?>
--EXPECT--
Caught: Throwing resource destructor called
