--TEST--
Observer: Generator with uncaught exception
--EXTENSIONS--
crex_test
--INI--
crex_test.observer.enabled=1
crex_test.observer.observe_all=1
crex_test.observer.show_return_value=1
--FILE--
<?crx
function fooResults() {
    yield 0;
    yield 1;
    throw new RuntimeException('Oops!');
}

function doSomething() {
    $generator = fooResults();
    foreach ($generator as $value) {
        echo $value . CRX_EOL;
    }

    return 'You should not see this';
}

echo doSomething() . CRX_EOL;
?>
--EXPECTF--
<!-- init '%s' -->
<file '%s'>
  <!-- init doSomething() -->
  <doSomething>
    <!-- init fooResults() -->
    <fooResults>
    </fooResults:0>
0
    <fooResults>
    </fooResults:1>
1
    <fooResults>
      <!-- init Exception::__main() -->
      <Exception::__main>
      </Exception::__main:NULL>
      <!-- Exception: RuntimeException -->
    </fooResults:NULL>
    <!-- Exception: RuntimeException -->
  </doSomething:NULL>
  <!-- Exception: RuntimeException -->
</file '%s'>
<!-- init Exception::__toString() -->
<Exception::__toString>
  <!-- init Exception::getTraceAsString() -->
  <Exception::getTraceAsString>
  </Exception::getTraceAsString:'#0 %s(%d): fooResults()
#1 %s(%d): doSomething()
#2 {main}'>
</Exception::__toString:'RuntimeException: Oops! in %s%eobserver_generator_%d.crx:%d
Stack trace:
#0 %s%eobserver_generator_%d.crx(%d): fooResults()
#1 %s%eobserver_generator_%d.crx(%d): doSomething()
#2 {main}'>

Fatal error: Uncaught RuntimeException: Oops! in %s%eobserver_generator_%d.crx:%d
Stack trace:
#0 %s%eobserver_generator_%d.crx(%d): fooResults()
#1 %s%eobserver_generator_%d.crx(%d): doSomething()
#2 {main}
  thrown in %s%eobserver_generator_%d.crx on line %d
