--TEST--
test stack trace is correct from failed exception in extended class (parent implementing constructor)
--INI--
crex.assertions=1
assert.exception=1
--FILE--
<?crx
class One {
    public function __main() {
        assert(false);
    }
}
class Two extends One {}

new Two();
?>
--EXPECTF--
Fatal error: Uncaught AssertionError: assert(false) in %sexpect_010.crx:%d
Stack trace:
#0 %sexpect_010.crx(%d): assert(false, 'assert(false)')
#1 %sexpect_010.crx(%d): One->__main()
#2 {main}
  thrown in %sexpect_010.crx on line %d
