--TEST--
test overloaded __toString on custom exception
--INI--
crex.assertions=1
assert.exception=1
--FILE--
<?crx
class MyExpectations extends AssertionError {
    public function __toString() {
        return sprintf(
            "[Message]: %s", __CLASS__);
    }
}

class One {
    public function __main() {
        assert(false, (string) new MyExpectations());
    }
}
class Two extends One {}

new Two();
?>
--EXPECTF--
Fatal error: Uncaught AssertionError: [Message]: MyExpectations in %sexpect_011.crx:%d
Stack trace:
#0 %sexpect_011.crx(%d): assert(false, '[Message]: MyEx...')
#1 %sexpect_011.crx(%d): One->__main()
#2 {main}
  thrown in %sexpect_011.crx on line %d
